/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package cloud.cleo.connectgpt;

import com.theokanning.openai.completion.chat.ChatMessage;
import java.time.Duration;
import java.time.Instant;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.LinkedList;
import java.util.List;
import software.amazon.awssdk.enhanced.dynamodb.extensions.annotations.DynamoDbAutoGeneratedTimestampAttribute;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.*;

/**
 * Object to track use of ChatGPT
 *
 * @author sjensen
 */
@DynamoDbBean
public class ChatGPTSessionState {

    private String phoneNumber;
    private LocalDate date;
    private List<ChatGPTMessage> messages;
    private Long counter;
    private Instant lastUpdate;
    private Long ttl;

    public ChatGPTSessionState() {
    }

    public ChatGPTSessionState(String phoneNumber) {
        this.phoneNumber = phoneNumber;
        this.date = LocalDate.now(ZoneId.of("America/Chicago"));
        this.messages = new LinkedList<>();
        this.messages.add(new ChatGPTMessage(ChatGPTMessage.MessageRole.system, "I am interacting via a telephone interface.  please keep answers short and concise"));

        // Expire entries after 60 days
        this.ttl = Instant.now().plus(Duration.ofDays(60)).getEpochSecond();
        this.counter = 0L;
    }

    /**
     * @return the phoneNumber
     */
    @DynamoDbPartitionKey
    public String getPhoneNumber() {
        return phoneNumber;
    }

    /**
     * @param phoneNumber the phoneNumber to set
     */
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }

    /**
     * @return the date
     */
    @DynamoDbSortKey
    public LocalDate getDate() {
        return date;
    }

    /**
     * @param date the date to set
     */
    public void setDate(LocalDate date) {
        this.date = date;
    }

    /**
     * @return the messages
     */
    public List<ChatGPTMessage> getMessages() {
        return messages;
    }

    /**
     * @param messages the messages to set
     */
    public void setMessages(List<ChatGPTMessage> messages) {
        this.messages = messages;
    }

    public void addUserMessage(String message) {
        messages.add(new ChatGPTMessage(ChatGPTMessage.MessageRole.user, message));
    }
    
    public void addSystemMessage(String message) {
        messages.add(new ChatGPTMessage(ChatGPTMessage.MessageRole.system, message));
    }

    public void addAssistantMessage(String message) {
        messages.add(new ChatGPTMessage(ChatGPTMessage.MessageRole.assistant, message));
    }

    @DynamoDbIgnore
    public List<ChatMessage> getChatMessages() {
        final var cms = new LinkedList<ChatMessage>();
        messages.forEach(m -> cms.add(new ChatMessage(m.getRole().toString(), m.getContent())));
        return cms;
    }

    public void incrementCounter() {
        counter = counter + 1L;
    }
    
    /**
     * @return the counter
     */
    public Long getCounter() {
        return counter;
    }

    /**
     * @param counter the counter to set
     */
    public void setCounter(Long counter) {
        this.counter = counter;
    }

    /**
     * @return the lastUpdate
     */
    @DynamoDbAutoGeneratedTimestampAttribute
    public Instant getLastUpdate() {
        return lastUpdate;
    }

    /**
     * @param lastUpdate the lastUpdate to set
     */
    public void setLastUpdate(Instant lastUpdate) {
        this.lastUpdate = lastUpdate;
    }

    /**
     * @return the ttl
     */
    public Long getTtl() {
        return ttl;
    }

    /**
     * @param ttl the ttl to set
     */
    public void setTtl(Long ttl) {
        this.ttl = ttl;
    }
}
